In [14]:
import numpy as np


In [15]:
arr1 = np.random.randint(0,256,size=(16,16))

In [16]:
arr1

array([[160,  21,  76,  68,  66, 116,  97,   1, 101,  40, 109, 169, 158,
         23, 243,  58],
       [113,  15, 254, 121, 165,  80, 195, 121, 206, 146, 155, 215,   9,
         98,  87,  88],
       [124,  71, 153,  49,  45,  73, 177, 230, 230, 248,  32,  53,  36,
        201,  75, 247],
       [ 30, 140, 190, 237,  30, 101,  50, 169, 124, 215, 134,  75, 145,
        179,  59, 132],
       [ 75, 146, 240,   9, 230,   0, 190, 181, 224,  56, 218, 211,  82,
         61,  68, 201],
       [100,  75, 178,  93, 253,  60,  64,  57,  17, 131,  97,  94,  15,
        234, 146, 242],
       [ 57, 220, 247, 201, 235, 147, 162,  68, 177,  93, 237,  74, 249,
        151, 164,  72],
       [165, 238, 134, 255, 231, 196, 159, 187,  84, 134,  42, 255, 101,
        216, 198,  93],
       [ 74, 205, 140, 130,  99, 119, 100, 192, 254, 243,  55,  10,  37,
          0,  29, 237],
       [209, 221, 139,  44, 214,   2, 163, 162, 213,  43, 242,   0, 199,
        126,  56, 228],
       [  3, 142, 133, 188,  1

In [17]:
arr2 = np.random.randint(0,256,size=(16,16))
arr2

array([[ 80, 145, 241, 136, 214,   6, 205, 180, 244, 204, 245,  48, 151,
         35, 222, 232],
       [161, 165, 134,  63, 180, 157,  95, 177, 173, 226, 159, 123, 243,
        185, 148, 209],
       [253,  41, 143, 128,   1,  90, 179, 195,  85,   7, 119, 228,  62,
        205, 192, 145],
       [ 81, 106, 238, 126,  61, 167,  87, 146,   6, 215, 248,  72, 170,
        149, 109, 234],
       [ 29, 112, 101,  14, 154,  68, 229, 163,  41, 161,  88,  67, 202,
        252, 159, 218],
       [161, 160, 131, 179,   5,  44, 136, 210, 126, 121,  86, 214, 106,
        253, 164, 108],
       [ 27, 156, 102, 173, 226, 181,  23,  23, 170, 124, 157,  32,  99,
        161, 193,  68],
       [ 63,  64,  24, 197, 146, 195, 221,   0,  20, 110, 117,  40, 156,
         52, 134, 215],
       [  7, 169, 160, 106,  53,  97, 180,  16, 246,  54, 249,  20,  88,
         81,  68, 224],
       [145, 221, 230, 253,  74, 194, 248,  67,  27, 238, 239, 231, 141,
        158, 225, 153],
       [184,  54,  64,  31,  7

In [18]:
arr3 = np.random.randint(0,256,size=(16,16))
arr3

array([[ 35,  53, 236, 134, 251, 151,  12, 140,  54, 226,   9, 228,  45,
         68, 164,  82],
       [171, 145,  67,  88, 126, 125,   0, 253,  39,  37, 189,  58, 157,
         42, 100, 201],
       [199, 105,  46, 219, 197, 212, 101, 123,  74, 136, 152,  94,  61,
        195,  26,  56],
       [179, 137, 184,  31,  64, 248, 110,  48, 192,  92,  95, 210, 187,
        255,  56,  19],
       [ 70, 247,  56, 228,  49,  31, 181, 224,  31, 238,  48, 249, 177,
        189, 112, 129],
       [246, 254, 142,  32, 168, 254, 115,  61,  10,  10, 161, 246, 146,
        247,  96,   5],
       [245,  71, 242,  65,  61, 232,  84, 161,  82,  57, 246,  40, 172,
         73, 253,  19],
       [101, 219, 179,  85, 152,  48, 196,  67, 211, 225, 158, 143, 231,
        115, 241, 112],
       [110,  95, 234, 128, 249, 211,  27, 105,  19, 204,  39, 164, 228,
        160, 126, 219],
       [167, 224,  22, 246,  45,  77, 121, 122, 250, 196,   1,  37, 163,
        207, 165, 167],
       [ 83, 130,  15, 115, 12

In [19]:
arr4 = np.random.randint(0,256,size=(16,16))
arr4

array([[ 94, 185, 243, 180, 132, 153, 108, 112, 202, 180, 126,  15, 202,
         23,  13, 142],
       [229, 228, 102,  43,  12,   7, 134,  37, 223, 201,  62,  17, 154,
        232, 188, 245],
       [243,   6, 185, 205,   5, 172, 221, 224, 201, 150, 133, 130,  17,
        135,  90, 196],
       [232, 232, 203, 239,   7,   2,  61, 237,  97,  99, 200, 131, 255,
        154, 106, 197],
       [189, 152,  99, 135,  17, 218,  55, 254, 196, 185,  63, 151, 142,
         98,  35,  38],
       [192,  96,  65, 177, 248, 149,  83,  31,  72, 226, 228,  44, 169,
        230, 130,  38],
       [101,  23,  56, 214, 222, 200, 214, 250,  28, 130,  98, 195, 240,
         40,  86,  26],
       [168,  11,  29,  41,  66, 166, 189, 184,  56, 217, 241,  73,  82,
         39,  54,  53],
       [200,  89, 227,  31, 130,  52,  57,  66, 167, 150,  17, 136, 225,
        120, 216,  44],
       [179,  70,  21,  28, 146,  76, 186, 236,  39, 116, 254, 112, 238,
         13, 234, 220],
       [165, 207, 123, 163,  7

In [20]:
blend1 = np.concatenate((arr1,arr2))

In [21]:
blend1

array([[160,  21,  76,  68,  66, 116,  97,   1, 101,  40, 109, 169, 158,
         23, 243,  58],
       [113,  15, 254, 121, 165,  80, 195, 121, 206, 146, 155, 215,   9,
         98,  87,  88],
       [124,  71, 153,  49,  45,  73, 177, 230, 230, 248,  32,  53,  36,
        201,  75, 247],
       [ 30, 140, 190, 237,  30, 101,  50, 169, 124, 215, 134,  75, 145,
        179,  59, 132],
       [ 75, 146, 240,   9, 230,   0, 190, 181, 224,  56, 218, 211,  82,
         61,  68, 201],
       [100,  75, 178,  93, 253,  60,  64,  57,  17, 131,  97,  94,  15,
        234, 146, 242],
       [ 57, 220, 247, 201, 235, 147, 162,  68, 177,  93, 237,  74, 249,
        151, 164,  72],
       [165, 238, 134, 255, 231, 196, 159, 187,  84, 134,  42, 255, 101,
        216, 198,  93],
       [ 74, 205, 140, 130,  99, 119, 100, 192, 254, 243,  55,  10,  37,
          0,  29, 237],
       [209, 221, 139,  44, 214,   2, 163, 162, 213,  43, 242,   0, 199,
        126,  56, 228],
       [  3, 142, 133, 188,  1

In [22]:
blend2 = np.concatenate((arr3,arr4))

In [23]:
blend2

array([[ 35,  53, 236, 134, 251, 151,  12, 140,  54, 226,   9, 228,  45,
         68, 164,  82],
       [171, 145,  67,  88, 126, 125,   0, 253,  39,  37, 189,  58, 157,
         42, 100, 201],
       [199, 105,  46, 219, 197, 212, 101, 123,  74, 136, 152,  94,  61,
        195,  26,  56],
       [179, 137, 184,  31,  64, 248, 110,  48, 192,  92,  95, 210, 187,
        255,  56,  19],
       [ 70, 247,  56, 228,  49,  31, 181, 224,  31, 238,  48, 249, 177,
        189, 112, 129],
       [246, 254, 142,  32, 168, 254, 115,  61,  10,  10, 161, 246, 146,
        247,  96,   5],
       [245,  71, 242,  65,  61, 232,  84, 161,  82,  57, 246,  40, 172,
         73, 253,  19],
       [101, 219, 179,  85, 152,  48, 196,  67, 211, 225, 158, 143, 231,
        115, 241, 112],
       [110,  95, 234, 128, 249, 211,  27, 105,  19, 204,  39, 164, 228,
        160, 126, 219],
       [167, 224,  22, 246,  45,  77, 121, 122, 250, 196,   1,  37, 163,
        207, 165, 167],
       [ 83, 130,  15, 115, 12

In [24]:
blend_end = np.concatenate((blend1,blend2))

In [25]:
blend_end

array([[160,  21,  76, ...,  23, 243,  58],
       [113,  15, 254, ...,  98,  87,  88],
       [124,  71, 153, ..., 201,  75, 247],
       ...,
       [184, 243, 214, ...,   5, 109, 178],
       [ 18, 154, 129, ..., 167,  18, 235],
       [125, 117,   1, ..., 162,  60, 185]])